apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elasticsearch
  labels:
    app: elasticsearch
    role: client
spec:
  type: LoadBalancer
  loadBalancerIP: 10.128.1.5
  selector:
    app: elasticsearch
    role: client
  ports:
  - port: 9200
    targetPort: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-discovery
  namespace: elasticsearch
  labels:
    component: elasticsearch
    role: master
spec:
  type: NodePort
  selector:
    app: elasticsearch
    role: master
  ports:
  - name: transport
    port: 9300
    protocol: TCP
